spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        In-stream:
          destination: greetings
          contentType: application/json
        Out-stream:
          destination: greetings
          contentType: application/json